update version react(16.8.6) & react-dom(16.12.0) to avoid project st…
meteor/simple-todos-react pull request #91
Opened 2019-11-27 19:44 UTC by kakadais

# Before
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g9d7yp31oij31b30u04qp.jpg)

# After

![](https://tva1.sinaimg.cn/large/006y8mN6gy1g9d7xp6sakj31b30u0tvq.jpg)

# Changed Version
"react": "^16.8.6"
"react-dom": "^16.12.0"

2019-11-28 18:19 UTC, filipenevola requested changes
@kakadais thanks!

can you sign the CLA if you agree and also use "react": "^16.12.0" instead of 16.8.5?

2019-12-19 09:20 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/simple-todos-react?pullRequest=91) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/simple-todos-react?pullRequest=91) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/simple-todos-react?pullRequest=91) it.</sub>

2020-03-23 08:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meteor/simple-todos-react?pullRequest=91) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meteor/simple-todos-react?pullRequest=91) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meteor/simple-todos-react?pullRequest=91) it.</sub>

2020-03-23 09:02 UTC, kakadais commented
@filipenevola Sorry to lost this message-

2020-04-01 14:20 UTC, filipenevola requested changes
Hi, we don't include .meteor/version on purpose to populate this in the first start. I just saw now that you have included it. Can you please remove?

2020-07-17 20:31 UTC, closed without merging